usuarios:
    resource: "@UsuariosBundle/Controller/"
    type:     annotation
    prefix:   /usuarios

juegos:
    resource: "@JuegosBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /usuarios/logout
